// Terms of Service and Privacy Policy source text, rendered as Markdown by
// the /terms and /privacy pages (see src/components/legal/LegalContent.tsx).
// These are a solid starting point drafted against Anthropic's API terms,
// Stripe's website requirements, and GDPR/CCPA.
//
// Runtime-substituted tokens (renderLegalDoc() in ./config.ts):
//   {{LEGAL_ENTITY}}  {{BUSINESS_ADDRESS}}  {{JURISDICTION}}  — REQUIRED env;
//     the pages 404 (and their UI links hide) until all three are set.
//   {{CONTACT_EMAIL}}  {{PRIVACY_EMAIL}}  — optional env, default to the
//     support@/privacy@ addresses at the site's domain.
//
// All other former [PLACEHOLDER]/[— confirm] items (retention periods,
// transfer mechanisms, R2 region, Stripe location, minimum age) have been
// filled in with concrete values verified against the deployment config.
// This is still a starting point — have a lawyer review before relying on it.

export const TERMS_MARKDOWN = `# Terms of Service

_Effective date: 2026-06-05_

These Terms of Service ("Terms") govern your access to and use of sheetllm.com and the sheet-llm web application (the "Service"), operated by {{LEGAL_ENTITY}} ("we", "us", or "our"). Please read them carefully. If you do not agree, do not use the Service.

## 1. Acceptance of These Terms

By accessing or using the Service — including by using it anonymously, by creating an account, or by completing a purchase — you agree to be bound by these Terms and by our Privacy Policy, which is incorporated by reference.

When you create an account, you confirm your agreement by an affirmative action (for example, checking an "I agree" box). When you purchase credits, you confirm your agreement again at checkout, including acceptance of the Refund Policy in Section 11. We may record the date and time of your acceptance.

If you use the Service on behalf of an organization, you represent that you are authorized to bind that organization, and "you" includes that organization.

## 2. Eligibility and Age

You must be at least 16 years old to use the Service, or at least 13 with the verifiable consent of a parent or legal guardian where your local law permits use at that age. If you are below the age of majority where you live, you may use the Service only with the involvement and consent of a parent or legal guardian who agrees to these Terms on your behalf.

Separately from this contractual minimum, data-protection law may require parental or guardian consent before we process a minor's personal data — for example, under GDPR Article 8, where we rely on consent for an EU child below the applicable age (16 in Germany, where our servers are located). Our handling of children's data, including any parental-consent requirements, is described in our Privacy Policy.

The Service is not directed to children below the applicable minimum age, and we do not knowingly collect their personal data.

You also represent that you are not barred from using the Service under any applicable sanctions, trade, or export-control laws, and that you will not use the Service where it is prohibited by law.

## 3. The Service and How It Works

sheet-llm lets you compose and edit music notation with the help of artificial intelligence. You type natural-language requests; the Service sends those requests, together with relevant score and chat content, to Anthropic's Claude AI to generate or edit a musical score. The Service also supports manual notation editing, playback, and importing and exporting scores.

**You are interacting with an AI system, not a human.** The notation, edits, suggestions, and any explanatory text the Service produces in response to your requests ("AI Outputs") are generated by AI. We also display this disclosure in the product at the start of every chat session, for anonymous, free, and Pro users alike.

We may change, add, remove, or discontinue features of the Service over time, as described in Section 18.

## 4. AI Output Accuracy — No Reliance

**AI Outputs may be inaccurate, incomplete, or misleading.** This includes generated notation, musical or music-theory statements, and any other factual assertions. AI Outputs are provided "as is."

You should not rely on any factual assertion in an AI Output without independently checking its accuracy. We do not warrant that AI Outputs are musically correct, theoretically sound, original, non-infringing, or fit for any particular performance, publication, or commercial use.

The Service is a creative music-notation tool. It is **not** a source of legal, medical, financial, employment, or other professional advice, and it is not intended for high-risk decision-making. You are responsible for evaluating whether any AI Output is appropriate before you use or share it.

## 5. Accounts, Authentication, and Anonymous Use

You can use the Service anonymously, or you can create an optional account using an email address and password or by signing in with Google. Email verification may be required for some actions, and we send verification and password-reset messages by email.

You are responsible for keeping your account credentials secure and for all activity under your account. Tell us promptly if you suspect unauthorized use. We use Argon2id to hash passwords and Cloudflare Turnstile to help distinguish humans from bots. Turnstile and our other security measures process IP addresses and request metadata, as described in our Privacy Policy. No security measure is perfect.

If you use the Service anonymously, these Terms still bind you through your use of the Service. Anonymous use does not create an account, so the self-service export and deletion endpoints in Section 17 are not available to you; however, you can still exercise data-protection rights over any data tied to you (such as IP-based abuse-prevention records) by contacting {{PRIVACY_EMAIL}}. Retention of anonymous quota and IP data is described in our Privacy Policy.

## 6. Your Content and License to Us

You retain ownership of the content you provide, including your natural-language prompts, the music notation you enter or import, and your scores and chat messages ("Your Content").

You grant us a limited, non-exclusive, worldwide, royalty-free license to host, store, process, transmit, back up, and display Your Content **solely** to operate, secure, support, and maintain the Service. This license expressly includes transmitting your prompts and score content to Anthropic to generate AI Outputs, as described in our Privacy Policy. We do **not** use Your Content to train AI models, and we do not use Your Content for advertising. We do not sell Your Content, and we do not share it for cross-context behavioral advertising. Any operational use to maintain or debug the Service is limited to that purpose and is described in our Privacy Policy.

You represent that you have the rights necessary to provide Your Content and to grant this license, and that Your Content does not infringe anyone's rights or violate any law.

## 7. Ownership of AI Outputs

As between you and us, and only to the extent we actually hold any right, title, or interest in the AI Outputs generated for you, we assign that interest to you. We make **no representation that we own any assignable rights** in AI Outputs, and ownership of AI Outputs is ultimately governed by Anthropic's customer terms. This is not a warranty of clean or exclusive title. Subject to these Terms, you may use your AI Outputs freely, including commercially.

Please understand two important caveats:

- **Copyright may not exist.** Under current U.S. Copyright Office guidance, material generated solely from prompts generally is not protected by copyright, because it lacks sufficient human authorship. Copyright may attach only to your own creative contributions (for example, manual edits, arrangement, or original melody or lyrics that you author). We do not warrant that any AI Output is copyrightable, original, registrable, or non-infringing, and nothing here is legal advice.
- **Outputs may not be unique.** The AI may generate the same or similar output for other users. Your rights in AI Outputs are non-exclusive, and we do not provide any intellectual-property indemnity for AI Outputs.

## 8. Acceptable Use

You must use the Service lawfully and consistently with **Anthropic's Usage Policy** (currently at https://www.anthropic.com/legal/aup). Because Anthropic's Claude AI powers the Service, your use must comply with that policy; we provide the link for context, and where it materially changes we will use reasonable efforts to make the current version available to you. The prohibitions below restate, in plain language, the substance of what is not allowed; they are illustrative and not exhaustive. Among other things, you must not use the Service to:

- do anything illegal, or facilitate illegal activity;
- harass, abuse, threaten, defame, or promote harm to others, or promote suicide, self-harm, or harassment;
- engage in fraud, deception, or impersonation;
- create or distribute malware, or interfere with the security or integrity of any system or critical infrastructure;
- generate, solicit, or distribute child sexual abuse material (CSAM) or any content that sexually exploits minors, or generate sexual content involving non-consenting persons;
- develop, design, or facilitate weapons, including CBRN (chemical, biological, radiological, or nuclear) weapons, or other activities that cause serious harm;
- interfere with elections or political processes, including voter suppression or manipulation;
- conduct unlawful surveillance, location tracking, biometric tracking, or facial recognition without consent;
- generate misinformation or content intended to deceive in a way that causes harm;
- violate the privacy or data-protection rights of others;
- infringe intellectual-property rights, including using the Service to launder, reproduce, or recreate third-party copyrighted compositions, or to process content you do not have the rights to use; or
- attempt to misuse, manipulate, or extract the underlying AI model.

**No resale or proxy access.** You may not resell, sublicense, rent, or redistribute the Service or the underlying Claude API, provide bulk or programmatic access to it, scrape the Service, or use it as a proxy or conduit to access raw Claude or other AI-model capabilities.

**No circumvention.** You may not circumvent or attempt to circumvent credit, quota, or rate limits, bot challenges (including Turnstile), or other access or abuse controls, and you may not reverse engineer the Service except to the extent this restriction is prohibited by law.

## 9. Anti-Abuse, Suspension, and Termination

To protect the Service and its users, we use automated abuse-prevention measures, including per-user and per-IP rate limiting, bot/IP-risk scoring (such as Tor and datacenter-ASN checks), and Cloudflare Turnstile challenges. These may slow, challenge, or block requests. These measures process IP addresses and request metadata; we do this on the basis of our legitimate interest in keeping the Service secure and preventing abuse (GDPR Article 6(1)(f)). Our Privacy Policy describes this processing, Cloudflare's role as a processor, and how long we retain quota and IP counters.

We may suspend, throttle, or terminate your access (in whole or in part), and may decline to generate output, if we reasonably believe you have violated these Terms or Anthropic's Usage Policy, engaged in fraud, abuse, or chargeback misuse, or where we are required to do so by law or by our own provider agreements.

You may stop using the Service or close your account at any time. Before deletion, you can export your scores (see Section 17). On termination:

- if we terminate **for cause** (such as a violation of these Terms), your credits are forfeited;
- if we terminate **without cause** or discontinue the Service, your unused credits remain usable for any wind-down period we provide, and — consistent with Sections 11 and 18 — we will refund the cash-equivalent value of your validly purchased, unused credits (1 credit = 1 US cent) to your original payment method, subject to applicable law and to the limits in those Sections; we will not simply revoke validly purchased, unused credits;
- you can delete your account data and content yourself through the erasure process at \`/api/me/delete\` (a user-initiated cascade-delete), and we otherwise retain and delete data in accordance with our Privacy Policy's retention schedule; we do not represent that every termination triggers automatic immediate deletion; and
- Stripe financial and tax records are retained as required by law, even after account deletion.

## 10. Credits, Pricing, and Payments

The Service offers a bounded **free tier** that provides short AI generation at no charge, and a one-time **free full piece** per verified account.

"Pro" AI generation (such as longer or whole-score generation) is paid for with prepaid **credits**:

- **1 credit = 1 US cent.** All prices and balances are in **US dollars (USD)**, and charges are processed in USD.
- Credits are sold in packs of **$5, $10, $20, and $50 USD**, with escalating bonus credits per pack as shown at checkout. Bonus credits and the free-piece offer are **promotions**, available to verified accounts, one-time where stated, and subject to change.
- **Credits are a closed-loop service entitlement.** They have **no cash value** in ordinary use, are **not money, a gift card, stored value, or e-money**, are **not redeemable for cash** (except as expressly provided in Sections 9 and 11), and may be used only within the Service to unlock features.
- Credits **never expire** and are **non-transferable**.
- **Auto-refill is opt-in and off by default.** If you enable it, you choose and are shown both (a) the low-balance threshold that triggers a top-up and (b) the USD amount/pack purchased each time. When your balance reaches your chosen threshold, that same USD amount is charged to buy more credits, and the same amount applies until you change or disable it. You can disable auto-refill at any time in your account settings; it is not a subscription, and each top-up is a discrete purchase.

**Payments via Stripe.** Card payments are processed by Stripe through Stripe-hosted Checkout. Stripe receives your payment and card data directly; we never receive or store full card numbers, only Stripe identifiers and our own derived billing records. We currently accept major card brands, including Visa, Mastercard, and American Express; the brands available to you are also shown at checkout. The Service is served over HTTPS.

**Availability.** The Service and purchases may be unavailable where prohibited by applicable law, sanctions, or export controls.

## 11. Refunds and Cancellation

Credits are digital and are delivered instantly to your account balance, so there is nothing to ship or return.

Purchases are generally **final and non-refundable**, with limited exceptions: we will refund credits consumed because of **our service failures** — specifically a generation error, a timeout on our side, or a failure of our own validation. These refunds are subject to a **daily cap on the number of refunds** and a **daily credit ceiling**; the current limits are shown in your account/billing area before you purchase. The caps reset each day, and a legitimate service-failure refund that exceeds a day's cap remains claimable on a later day or by contacting support, so you are not permanently denied a refund for our own failures.

The following are **not** a service failure and are **not** refundable:

- requests you cancel or abort yourself;
- results that were successfully delivered to you; and
- dissatisfaction with the musical or creative quality, accuracy, originality, or usefulness of a successfully delivered AI Output. As explained in Section 4, AI Outputs may be inaccurate or imperfect, and this is not a generation error, timeout, or validation failure.

Approved refunds are returned as credits to your wallet (or, at our discretion, to your original payment method) within a reasonable time. If we permanently discontinue the Service, or terminate your access without cause, your unused credits will be refunded at cash-equivalent value (1 credit = 1 US cent) to your original payment method, subject to applicable law (see Sections 9 and 18). To request a refund, contact us at {{CONTACT_EMAIL}}.

**EU consumers — right of withdrawal.** If you are a consumer in the EU, you normally have 14 days to withdraw from a purchase of digital content. When you use credits to generate output immediately, you expressly request immediate performance and acknowledge that you lose your right of withdrawal for that digital content once it has been supplied. Credits you have not yet used may still be withdrawable within the 14-day period. Nothing in these Terms affects mandatory consumer rights that cannot be waived.

## 12. Anthropic Is Not a Party

The AI Outputs are generated using Anthropic's Claude AI. **Anthropic, PBC is not a party to these Terms, is not your counterparty, and is not liable to you** for the Service or for any AI Output. We — not Anthropic — are the party responsible to you under these Terms. Your use of the Service must comply with Anthropic's Usage Policy, as set out in Section 8.

## 13. Disclaimer of Warranties

**THE SERVICE AND ALL AI OUTPUTS ARE PROVIDED "AS IS" AND "AS AVAILABLE."**

To the fullest extent permitted by law, we provide the Service and AI Outputs without warranties of any kind, whether express, implied, or statutory, and we disclaim all implied warranties, including the implied warranties of merchantability, fitness for a particular purpose, and non-infringement.

We do not warrant that the Service will be uninterrupted, error-free, or secure, or that AI Outputs will be accurate, correct, original, or fit for any purpose.

Nothing in this section limits any warranty or right that cannot be excluded under applicable law, including mandatory consumer-protection warranties. Where the law does not allow some of these exclusions, they apply to you only to the extent permitted.

## 14. Limitation of Liability

**TO THE FULLEST EXTENT PERMITTED BY LAW, OUR LIABILITY IS LIMITED AS SET OUT BELOW.**

To the fullest extent permitted by law, we will not be liable for any indirect, incidental, special, consequential, or punitive damages, or for any loss of profits, revenue, data, or goodwill, arising out of or relating to the Service or these Terms.

Our total aggregate liability arising out of or relating to the Service or these Terms will not exceed the greater of (a) the amounts you paid us in the 12 months before the event giving rise to the claim, or (b) USD $100.

The exclusion of liability for loss of "data" above does **not** limit our responsibility for negligent loss or corruption of the musical scores you have stored with us, which is the core content you entrust to the Service; we maintain encrypted backups of your stored data as part of normal operation, and our liability for such loss remains subject to the aggregate cap above except where the law does not allow it.

These limits do not apply to liability that cannot be excluded or limited under applicable law — for example, liability for death or personal injury caused by negligence, for fraud or fraudulent misrepresentation, for gross negligence or willful misconduct, or any liability that may not be excluded under applicable consumer-protection or data-protection law. If you are a consumer, you keep all mandatory rights the law gives you.

## 15. Indemnification

To the extent permitted by law, you agree to indemnify and hold us harmless from third-party claims, damages, and reasonable expenses arising out of (a) your misuse of the Service, (b) your violation of these Terms or Anthropic's Usage Policy, (c) Your Content or your use of AI Outputs in violation of any law or third-party right, or (d) your unlawful conduct.

This does not require you to indemnify us for our own negligence or misconduct, and it applies only to matters within your control.

## 16. Privacy and Data Processing

How we collect, use, and share personal data is described in our Privacy Policy. In summary:

- Your prompts and score content are transmitted to Anthropic, PBC to generate AI Outputs, under appropriate transfer safeguards (such as EU Standard Contractual Clauses) where applicable, as described in our Privacy Policy. Anthropic does not train on this content.
- Other service providers also process personal data on our behalf, including payment processing (Stripe), transactional email delivery (Brevo), hosting (Hetzner, in the EU), CDN, security, and bot mitigation (Cloudflare), encrypted backups (Cloudflare R2), and optional Google sign-in if you choose it. Some of these involve transfers outside your country, including to the US, under appropriate safeguards such as EU Standard Contractual Clauses.
- We do not sell personal data, and we do not share it for cross-context behavioral advertising (as those terms are defined under the CCPA/CPRA).

The full list of subprocessors, the international-transfer mechanisms, retention periods, the lawful bases for our processing, and your rights are set out in our Privacy Policy. Please read it to understand our data practices.

## 17. Data Export and Deletion

If you have an account, you can export your data at \`/api/me/export\` (GDPR Article 15 access) and request erasure of your account at \`/api/me/delete\` (GDPR Article 17), which cascade-deletes your user data. As noted above, Stripe financial and tax records are retained as a legal obligation even after deletion. Email verification may be required for some of these actions.

These self-service endpoints are not the only rights you have. Depending on where you live, you may also exercise rights of rectification, restriction, objection, and data portability, and, under the CCPA/CPRA, the rights to know, delete, and correct, and to opt out of the sale or sharing of personal information (we do not sell personal data and do not share it for cross-context behavioral advertising). If you use the Service anonymously and have no account, you can still make these requests over IP-tied records. To exercise any of these rights, contact {{PRIVACY_EMAIL}}. See the Privacy Policy for full details.

## 18. Changes to the Service and to These Terms

We may modify, suspend, or discontinue features of the Service at any time. If we permanently discontinue the Service, unused credits will be refunded at cash-equivalent value (1 credit = 1 US cent) to your original payment method, subject to applicable law, as set out in Sections 9 and 11.

We may also update these Terms. For material changes, we will give reasonable advance notice and will update the Effective date above. For account holders, we will notify verified accounts by email and/or by an in-app notice. For anonymous users, who cannot be emailed, material changes will be presented through an in-app acceptance gate rather than relying on continued use alone. Changes are prospective only — they do not apply retroactively, and they do not change the terms applicable to credits you have already purchased. If you do not agree to updated Terms, you should stop using the Service.

## 19. Governing Law and Disputes

These Terms are governed by the laws of {{JURISDICTION}}, without regard to its conflict-of-laws rules, and disputes will be subject to the courts of {{JURISDICTION}}.

If you are a consumer in the EU or UK (or elsewhere with similar protections), this choice of law and forum does not deprive you of the protection of mandatory consumer-protection rules of the country where you live. You retain the right to bring proceedings in, and to rely on the mandatory law of, your home courts, including under the Brussels Recast Regulation and Rome I where they apply. Nothing in these Terms waives any non-waivable statutory right.

## 20. Severability and Savings

If any provision of these Terms (or its application to any person or circumstance, such as to EU consumers) is found unenforceable, that provision will be limited or severed to the minimum extent necessary, and the remaining provisions will stay in full force. Your mandatory, non-waivable statutory rights prevail over any conflicting term in these Terms.

## 21. Contact and Operator Details

The Service is operated by {{LEGAL_ENTITY}}, {{BUSINESS_ADDRESS}}.

For questions, support, or refund requests, contact us at {{CONTACT_EMAIL}}. For privacy questions or to exercise data-protection rights, contact {{PRIVACY_EMAIL}}.
`

export const PRIVACY_MARKDOWN = `# Privacy Policy

_Effective date: 2026-06-05_

This Privacy Policy explains what personal data sheet-llm collects, why, who we share it with, and the choices and rights you have. It applies to sheetllm.com and the sheet-llm web app (the "Service").

sheet-llm is a web app for composing and editing music notation with AI assistance. You type natural-language requests, and the app uses Anthropic's Claude AI to generate and edit a musical score. You can also edit notation manually, play it back, and import or export files.

This policy works alongside our [Terms of Service](/terms), which include our acceptable-use rules (including the prohibitions in Anthropic's Usage Policy) and the full terms for credits, billing, and refunds.

## Who We Are (Controller)

The Service is operated by a small independent operator, **{{LEGAL_ENTITY}}**, at **{{BUSINESS_ADDRESS}}** ("we", "us", "our"). We are the controller of your personal data.

- Privacy contact: **{{PRIVACY_EMAIL}}**
- General/support contact: **{{CONTACT_EMAIL}}**

We have **not** appointed a Data Protection Officer; a formal DPO is not required for a service of this kind. For any privacy question, please use the contact above.

Our primary servers are hosted in **Germany (EU)**, so the EU General Data Protection Regulation (GDPR) applies. Some of our service providers process data in the United States; see "International Transfers" below.

## You Can Use sheet-llm Anonymously

You do not need an account to use the Service. In anonymous mode, we collect less account data — but some processing still happens, and you are not anonymous to us at the network level:

- Your IP address and request metadata are still handled for security, bot mitigation, and rate-limiting (see below).
- Any prompts and score content you submit are still sent to Anthropic to generate output, **including a transfer to the United States** — see "How Your Inputs Are Processed by AI" and "International Transfers".
- Scores, chat messages, and orchestrator turn records you create may still be stored server-side and linked to your IP address, which for an anonymous user may be the main identifier tied to your activity.

Because anonymous use has no account, there is no self-service \`/api/me/delete\`. To have anonymous content deleted, contact **{{PRIVACY_EMAIL}}**; see "How Long We Keep Your Data" for how long anonymous content and IP-linked data are retained.

Creating an account (optional) lets us store and manage your scores, history, tier, and (later) credits, and unlocks features that depend on an identity.

## What Personal Data We Collect

We collect only what we need to run the Service. Depending on how you use it, this may include:

**Account and authentication data (if you create an account)**
- Account ID
- Email address (stored lowercased) and an email-verified flag
- A password hash (using Argon2id) — we never store your password in plain text
- Google OAuth identity (the provider and your provider user ID) — only if you choose Google sign-in
- Display name
- Product tier
- Timestamps (e.g., created/updated)
- Authentication sessions and email-verification / password-reset tokens

**Your content**
- Your musical scores and score-version history
- Your chat messages and natural-language requests (prompts)

**AI processing records**
- Orchestrator turn records: the prompts/requests sent for generation and our internal cost for the turn (in micro-USD)

**Security, abuse-prevention, and quota data**
- Per-user and per-IP daily request-quota counters, which include your **IP address**
- Bot / IP-risk signals derived from your connection (including Tor / datacenter ASN checks) used for abuse and rate-limit decisions
- Request metadata processed by our CDN/security provider (Cloudflare)

**Billing data (when the paid credits feature is live)**
- Credit wallet balance and holds, credit purchases, an immutable usage ledger, refund counters, and a Stripe events inbox
- Stripe customer and payment identifiers and our derived billing records
- We do **not** receive or store your full card number — card and payment data go directly to Stripe (see "Subprocessors")

### Categories of Sources

We obtain personal data:
- **Directly from you** — account details, prompts, scores, chat messages
- **From your device/network automatically** — IP address and request metadata (via Cloudflare)
- **From Google** — your OAuth identity, only if you sign in with Google
- **From Stripe** — payment confirmation and identifiers, only when you make a purchase

## How Your Inputs Are Processed by AI

To generate or edit notation, **your prompts (your natural-language requests) and the score content needed to produce the output are transmitted to Anthropic, PBC, a U.S. company.** This is necessary to provide the AI features of the Service.

Anthropic processes this content to return a result to us. **Anthropic does not train its models on the content we send through its API.**

Because Anthropic is in the United States, this involves an EU-to-US transfer of your prompts and score content (see "International Transfers"). This is true even if you use the Service anonymously.

**You are interacting with an AI system (Claude), not a human.** Factual statements in AI outputs may be false, incomplete, or misleading, and should not be relied on without independent verification. The Service is not intended for legal, medical, financial, or other high-risk advice. The chat interface also shows you, at the start of each chat session, that you are interacting with an AI and that responses are AI-generated; this applies to anonymous users too. Fuller no-reliance and acceptable-use terms are in our [Terms of Service](/terms).

**Please do not include personal data about other people, or confidential information, in your prompts or scores** — prompt and score content is transmitted to Anthropic in the United States and stored in our orchestrator turn records.

We may also review prompts and content for compliance with our Terms and Anthropic's Usage Policy (for example, to detect illegal, abusive, fraudulent, or other prohibited use); see the legal-bases table below.

## Why We Use Your Data and Our Legal Bases

| Purpose | What this covers | Legal basis (GDPR Art. 6) |
|---|---|---|
| Providing the Service | Account creation/login, storing your scores and history, generating/editing notation via AI, playback, import/export | Contract — Art. 6(1)(b) |
| Account email | Email verification, password reset, essential transactional email | Contract — Art. 6(1)(b) |
| Abuse, bot, and IP-risk prevention | Per-user/per-IP quota counters, rate-limiting, bot/IP-risk scoring (incl. Tor/datacenter ASN checks), Cloudflare Turnstile, security monitoring, encrypted backups | Legitimate interests — Art. 6(1)(f): preventing abuse and fraud, keeping the Service secure and available |
| Acceptable-use / policy enforcement | Reviewing prompts and content for compliance with our Terms and Anthropic's Usage Policy (no illegal/abusive/fraud/malware/CSAM/weapons/etc. use) | Legitimate interests — Art. 6(1)(f) (keeping the Service lawful and safe) and, where applicable, Legal obligation — Art. 6(1)(c) |
| Billing and credits | Processing purchases, maintaining the credit wallet/ledger, fraud prevention on payments | Contract — Art. 6(1)(b) |
| Tax / accounting records | Retaining financial and transaction records | Legal obligation — Art. 6(1)(c) |
| Optional Google sign-in | Using your Google identity to authenticate you | Consent — Art. 6(1)(a), given when you choose Google sign-in |

Where we rely on **legitimate interests** (abuse prevention, bot and IP-risk scoring, rate-limiting, security, and acceptable-use enforcement), we have carried out a documented legitimate-interests balancing test weighing those interests against your rights. You have the right to object — see "Your Rights" below. We can provide a summary of the balancing test on request.

Each subprocessor (see below) is bound by a data-processing agreement that limits it to processing your data only on our instructions for the purposes above (and, for California, as a service provider that does not use your data for its own purposes), except where a provider acts as its own controller (see Stripe).

We do **not** use your data for advertising, and we do **not** build advertising or tracking profiles.

## Credits, Billing, and Refunds

The paid credits feature is **not yet live**. When it launches, the following will apply, and the full terms will be set out in our [Terms of Service](/terms) and shown at checkout:

- **Currency and price:** Credits are sold in **US Dollars (USD)**. **1 credit = 1 US cent.** Packs are sold at **$5, $10, $20, and $50 (USD)**, with escalating **bonus credits** on larger packs.
- **What credits are:** Credits are a prepaid **service entitlement with no cash value** (a closed-loop entitlement — not stored value or e-money). Credits **never expire**.
- **Bonus credits:** Bonus credits granted on larger packs are promotional. They carry no cash value and follow the same no-expiry and refund rules as purchased credits.
- **Auto-refill:** Auto-refill is **opt-in and off by default**.
- **Refunds:** Refunds are limited to **service failures on our side** (such as an error, timeout, or our own validation failure), subject to per-day count and credit ceilings. User-aborted requests and results we have already delivered are **not** refundable.
- **Free tier:** A bounded short generation is available at no charge, plus a one-time free full piece per verified account.
- **Payment methods:** The card brands and payment methods we accept are those shown at **Stripe Checkout**.

Card and payment data are handled directly by Stripe; we receive and store only Stripe identifiers and our derived billing records (see "Subprocessors").

## Automated Decision-Making and Bot / Abuse Detection

To protect the Service we use automated checks, including:
- **Cloudflare Turnstile** bot challenges
- Per-user and per-IP **rate-limiting and quota counters**
- **IP-risk scoring**, including Tor and datacenter ASN checks

These checks may slow down, challenge, or block requests we assess as abusive or automated. They are security measures and are **not intended to produce legal or similarly significant effects** about you. In any event, you can contact **{{CONTACT_EMAIL}}** for **human review** and to contest a decision, and if a paying user is wrongly blocked we will remedy it (for example, any credits involved are unaffected or restored).

## Who We Share It With (Subprocessors)

We use the following service providers (subprocessors) to run the Service. We **do not sell or share your personal data** (including as "sale" or "sharing" is defined under California law), and we do not use it for cross-context behavioral advertising.

| Subprocessor | Role | Data it receives | Location |
|---|---|---|---|
| **Anthropic, PBC** | AI generation (Claude) | Your prompts (natural-language requests) and the score content needed to generate output. **Does not train on API customer content.** | United States |
| **Stripe** | Payment processing | Card/payment data directly from you at checkout; we store only Stripe IDs + our derived records | United States (Stripe, Inc.) and Ireland/EU (Stripe Payments Europe, Ltd.) |
| **Brevo (Sendinblue)** | Transactional email (verification, password reset) | Email address and the transactional message itself (verification links, password-reset links, essential service notices) | EU (France) |
| **Cloudflare** | CDN, WAF, and bot mitigation (Turnstile) | IP address and request metadata | United States / global |
| **Cloudflare R2** | Encrypted database backups (via Litestream) | Encrypted backups of stored data | Cloudflare-managed (automatic region; may be outside the EU) |
| **Google** | OAuth sign-in — **only if you choose it** | Your Google account identity for authentication | United States |
| **Hetzner** | Hosting | All stored Service data | Germany (EU) |

**Stripe as an independent controller:** For payment processing and payment-fraud prevention, Stripe acts as its own controller and handles your card/payment data under [Stripe's privacy policy](https://stripe.com/privacy). sheet-llm only receives and stores Stripe identifiers and our derived billing records.

## International Transfers

Our primary hosting is in the **EU** (Hetzner, Germany). Encrypted backups are stored on **Cloudflare R2** in a Cloudflare-managed location (the bucket region is set to automatic), which may be outside the EU. Several providers process data in the **United States** — namely **Anthropic, Stripe, Cloudflare, and Google** (and Cloudflare R2 if its region is outside the EU).

For these transfers we rely on appropriate safeguards under Chapter V of the GDPR — primarily the **Standard Contractual Clauses (SCCs)** in each provider's data-processing agreement, supplemented by the EU–U.S. Data Privacy Framework where the provider is certified:

- **Anthropic:** Standard Contractual Clauses (SCCs)
- **Google:** Standard Contractual Clauses (SCCs)
- **Stripe:** Standard Contractual Clauses (SCCs)
- **Cloudflare (incl. R2):** Standard Contractual Clauses (SCCs)

You can request a copy of the relevant safeguards by contacting **{{PRIVACY_EMAIL}}**.

## How Long We Keep Your Data

| Data | Retention |
|---|---|
| Account data, scores, version history, chat messages (account users) | For the life of your account; deleted when you erase your account (subject to the backup window and the financial-records carve-out below) |
| Anonymous scores, chat messages, and orchestrator turn records | Retained until you ask us to delete them — anonymous use has no account, so there is no self-service deletion; we do not currently auto-expire anonymous content. Contact us to request deletion. |
| Orchestrator turn records (prompts + internal cost) | Kept as abuse- and cost-control records; for account users they are removed when you erase your account, and otherwise retained only while needed for those purposes |
| Per-IP / per-user quota counters and IP-risk signals | Short-term: about 25 hours (the 24-hour quota window plus a 1-hour grace), then automatically deleted on the next maintenance sweep |
| Encrypted backups | Rotate on a backup cycle; erased data ages out of backups within the retention window of up to 72 hours |
| Stripe financial / tax records | **Retained after account deletion** to meet legal and accounting obligations — for the period required by the applicable tax law of **{{JURISDICTION}}** (typically several years) |

Each retention period above reflects how long the data is needed for the stated purpose, plus any legal-retention requirement.

## Your Rights

Under the GDPR you have the right to:
- **Access** your data (Art. 15)
- **Rectify** inaccurate data (Art. 16)
- **Erase** your data (Art. 17)
- **Restrict** processing (Art. 18)
- **Data portability** (Art. 20)
- **Object** to processing based on legitimate interests, including our abuse/IP-risk scoring (Art. 21)
- Rights regarding **automated decision-making** (Art. 22)
- **Withdraw consent** at any time where we rely on it (e.g., Google sign-in)

**Self-service tools we have already built (account users):**
- **Export your data:** use the **"Export my data"** control in your account settings. This export gives you the data you provided and your stored content (your scores, history, and chat) for **portability (Art. 20)**. A full **access request (Art. 15)** — which also covers derived or observed data such as IP-risk signals, quota counters, and internal cost records — can be made by contacting **{{PRIVACY_EMAIL}}**; we will provide a complete copy.
- **Delete your account:** use the **"Delete account"** control in your account settings. This cascade-deletes your user data (scores, history, chat, account records). Note: **Stripe financial/tax records are retained** after deletion on a legal-obligation basis, and erased data persists in encrypted backups until the backup window rotates.

_(For developers: these controls are backed by the \`/api/me/export\` and \`/api/me/delete\` endpoints.)_

**Right to object (Art. 21):** You can object to processing we base on legitimate interests. For security, abuse prevention, and acceptable-use enforcement, we may continue processing where we can demonstrate compelling legitimate grounds that override your objection (for example, to keep the Service secure and lawful). We can provide a summary of our legitimate-interests balancing test on request.

Email verification may be required before we act on certain requests, to confirm it's really you.

We aim to respond within **one month** (GDPR). You can also **lodge a complaint** with a data-protection supervisory authority — your local authority in your country of residence, or the authority for the operator's place of establishment (to be identified once **{{LEGAL_ENTITY}}** / **{{BUSINESS_ADDRESS}}** is confirmed).

**If you are in California (CCPA/CPRA):** you have the right to know/access, delete, and correct your personal information, to opt out of the sale or sharing of personal information, and to limit the use of sensitive personal information, and you will not be discriminated against for exercising these rights. **We do not sell or share your personal information**, so no opt-out is needed. The only arguably "sensitive personal information" we process is your **account log-in credentials** (your Argon2id password hash and related session/access tokens), which we use **solely to authenticate you and secure your account** — a permitted business purpose that does not trigger the right to limit use, so there is no "Limit" action to take. The data categories we collect map to: identifiers, internet/network activity, commercial information, and your own content. You can use the same export/delete tools above; we aim to respond within **45 days**.

## Cookies and Local Storage

We use only **strictly necessary** and **security** technologies:
- **Session / authentication** cookies or tokens to keep you signed in. These are strictly necessary to provide the Service you request and are exempt from consent.
- **Cloudflare** and **Turnstile** cookies used specifically to mitigate bots and abuse and to keep the Service secure. We rely on these for that security purpose; they are not used for advertising, analytics, or profiling.

We do **not** use advertising, analytics, or tracking/profiling cookies. If we ever add non-essential cookies, we will ask for your consent first.

## Security

We take reasonable technical and organizational measures to protect your data, including:
- **HTTPS/TLS** encryption in transit
- **Argon2id** password hashing
- **Encrypted database backups** (via Litestream to Cloudflare R2)
- **Cloudflare WAF**, Turnstile, and rate-limiting / abuse controls
- Card data handled by **Stripe-hosted Checkout** — we never store full card numbers

No method of transmission or storage is completely secure, so we cannot guarantee absolute security.

## Children

The Service is **not directed to children**. You must be at least **16** years old to use the Service. Separately, where any processing is based on your consent (for example, Google sign-in), and you are below the digital-consent age in your country, a parent or guardian must provide that consent on your behalf. We do not knowingly collect personal data from anyone below the applicable age. If you believe a child has provided us data, contact **{{PRIVACY_EMAIL}}** and we will delete it.

## Changes to This Policy

We may update this Privacy Policy from time to time. For material changes, we will give reasonable notice (for example, by email to verified accounts and/or an in-app notice) and update the Effective date above. Changes apply going forward.

## How to Contact Us

- Privacy questions: **{{PRIVACY_EMAIL}}**
- General/support: **{{CONTACT_EMAIL}}**
- Terms of Service (including acceptable use and credits/refund terms): [/terms](/terms)
- Operator: **{{LEGAL_ENTITY}}**, **{{BUSINESS_ADDRESS}}**
- Governing law / jurisdiction: **{{JURISDICTION}}** _(see our Terms of Service)_
`
